<?php

namespace App\Form;

use App\Entity\Champs;
use App\Entity\FichePerso;
use App\Entity\TypeInfo;
use Doctrine\DBAL\Types\TextType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ChampFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('label', null,[
                'label' => 'Nom du champ : ',
            ])
            ->add('valeurTexte', null,[
                'label' => 'Valeur du champ : ',
            ])
            ->add('valeurArea', TextareaType::class,[
                'label' => 'Valeur du champ : ',
                'required' => false
            ])
            ->add('fichePerso', EntityType::class,[
                'class' => FichePerso::class,
                'attr' => ['type' => 'hidden']
            ])
            ->add('typeChamp', ChoiceType::class,[
                'label' => 'Type de champ de saisie : ',
                'choices' => [
                    'champ de texte' => 'text',
                    'zone de texte' => 'textArea'
                ]
            ])
            ->add('typeInfo',EntityType::class,[
                'label' => 'Type d\'information : ',
                'class' => TypeInfo::class,
                'choice_label' => 'label'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Champs::class,
        ]);
    }
    public function getBlockPrefix()
    {
        return parent::getBlockPrefix(); // TODO: Change the autogenerated stub
    }
}
